#
# lua Travis-CI Hook
#

language: csharp

before_install:
  - git submodule update --init --recursive
# We need CMake, Mono and NUnit
install:
  - sudo apt-get install nunit

script:
  - ./run_all.linux.sh

# Execute additional tests or commands
#after_script:
#  - [run additional test commans]

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  recipients:
    - ryan.thomann@gmail.com
  email:
    on_success: change
    on_failure: always
